name: 562 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: '**/go.sum'
