name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: priyagupta108/setup-go@fix-manifest-error-handling
      with:
        go-version: '1.24'
        cache-dependency-path: '**/go.sum'
